productline2(L):-
L=[CS,U1,SHARING_SYSTEM,RATING, COMMENTS,PRODUCT_MANAGEMENT, COMMENT_MANAGEMENT, U4, COMMENT_MANAGEMENT, SHIPPING, LOGIN, BASIC_VIEW, USER_MANAGEMENT, U3,ONLINEPAYMENTE, OFFICEPAYMENTE, RATING, DEMO_DATA, U2, LOGIN, ACCOUNT, CONTACT_US,DATA_BASE_MANAGENT],
fd_domain(L,0,1),

%U1=Product, listProduct,productModel
%U2=Use, User_model
%U3=Shop,Cart
%U4=WebManagement, Basic_view
CS #=1,
CS #=U1,
CS #=U2,
CS #=U3,
CS #=U4,
CS #=DATA_BASE_MANAGENT,
CS #=BASIC_VIEW,
CS #>=SHARING_SYSTEM,
CS #>=RATING,
CS #>=COMMENTS,
CS #>=PRODUCT_MANAGEMENT,
CS #>=COMMENT_MANAGEMENT,
CS #>=U4,
CS #>=SHIPPING,
CS #>=LOGIN,
CS #>=SHIPPING,
CS #>=USER_MANAGEMENT,
CS #>=U3,
CS #>=ONLINEPAYMENTE,
CS #>=OFFICEPAYMENTE,
CS #>=RATING,
CS #>=DEMO_DATA,
CS #>=ACCOUNT,
CS #>=CONTACT_US,

PRODUCT_MANAGEMENT #==>U4,
COMMENT_MANAGEMENT #==>U4,
LOGIN #==>U4,
USER_MANAGEMENT #==>U2,
ONLINEPAYMENTE #==>U3,
OFFICEPAYMENTE #==>U3,
LOGIN #==>U2,
ACCOUNT #==>U2,
%U1=((PRODUCT #/\lIST_PRODUCT) #/\PRODUCT_MODEL),
fd_labeling(L).
%productline2(L).
















